AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud Posse Terraform AWS Backend'

Parameters:
  StackName:
    Type: String
    Description: (Required) Name of the stack (used as prefix for all resources). This must be globally unique

  # State Backend Parameters
  CreateStateBackend:
    Type: String
    Description: Set to 'true' to create state backend resources (S3 bucket, DynamoDB table, KMS key), 'false' to skip
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  BucketName:
    Type: String
    Description: Name of the S3 bucket for Terraform state
    Default: tfstate

  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table for state locking
    Default: tfstate

  KmsKeyAliasName:
    Type: String
    Description: Alias for the KMS key used for encryption
    Default: tfstate

  # Plan File Storage Parameters
  CreatePlanFileStorage:
    Type: String
    Description: Set to 'true' to create plan file storage resources (S3 bucket, DynamoDB table), 'false' to skip
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  PlanBucketName:
    Type: String
    Description: Name of the S3 bucket for Terraform plan files
    Default: tfplan

  PlanDynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table for Terraform plan metadata
    Default: tfplan

  # GitHub Access Parameters
  CreateGitHubAccess:
    Type: String
    Description: Set to 'true' to create GitHub access resources (OIDC provider, IAM role), 'false' to skip
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  CreateOIDCProvider:
    Type: String
    Description: Set to 'true' to create the GitHub OIDC provider, 'false' to skip (if it already exists)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  GitHubOrg:
    Type: String
    Description: GitHub organization or username
    Default: cloudposse

  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: "*"

  GitHubRoleName:
    Type: String
    Description: Name of the IAM role for GitHub Actions
    Default: github-actions

Conditions:
  ShouldCreateStateBackend: !Equals [!Ref CreateStateBackend, 'true']
  ShouldCreatePlanFileStorage: !Equals [!Ref CreatePlanFileStorage, 'true']
  ShouldCreateGitHubAccess: !Equals [!Ref CreateGitHubAccess, 'true']
  ShouldCreateOIDCProvider: !And 
    - !Equals [!Ref CreateGitHubAccess, 'true']
    - !Equals [!Ref CreateOIDCProvider, 'true']

Resources:
  # ============================================================================
  # TERRAFORM BACKEND
  # ============================================================================
  
  StateBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateStateBackend
    Properties:
      BucketName: !Sub '${StackName}-${BucketName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90

  KmsKey:
    Type: AWS::KMS::Key
    Condition: ShouldCreateStateBackend
    Properties:
      Description: !Sub 'KMS key for ${StackName} state encryption'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow S3 to use the key
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Condition: ShouldCreateStateBackend
    Properties:
      AliasName: !Sub 'alias/${StackName}-${KmsKeyAliasName}'
      TargetKeyId: !Ref KmsKey

  StateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreateStateBackend
    Properties:
      Bucket: !Ref StateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal:
              AWS: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${StateBucket}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption':
                  - AES256
                  - aws:kms
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal:
              AWS: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${StateBucket}/*'
            Condition:
              StringEquals:
                's3:x-amz-server-side-encryption': ''
          - Sid: EnforceTlsRequestsOnly
            Effect: Deny
            Principal:
              AWS: '*'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${StateBucket}'
              - !Sub 'arn:aws:s3:::${StateBucket}/*'
            Condition:
              Bool:
                aws:SecureTransport: false

  StateDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Condition: ShouldCreateStateBackend
    Properties:
      TableName: !Sub '${StackName}-${DynamoDBTableName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !GetAtt KmsKey.Arn

  # ============================================================================
  # PLAN FILE STORAGE
  # ============================================================================

  PlanBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreatePlanFileStorage
    Properties:
      BucketName: !Sub '${StackName}-${PlanBucketName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If 
                - ShouldCreateStateBackend
                - aws:kms
                - AES256
              KMSMasterKeyID: !If 
                - ShouldCreateStateBackend
                - !GetAtt KmsKey.Arn
                - !Ref AWS::NoValue
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90

  PlanBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreatePlanFileStorage
    Properties:
      Bucket: !Ref PlanBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTlsRequestsOnly
            Effect: Deny
            Principal:
              AWS: '*'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${PlanBucket}'
              - !Sub 'arn:aws:s3:::${PlanBucket}/*'
            Condition:
              Bool:
                aws:SecureTransport: false

  PlanDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Condition: ShouldCreatePlanFileStorage
    Properties:
      TableName: !Sub '${StackName}-${PlanDynamoDBTableName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: pr
          AttributeType: N
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: pr-createdAt-index
          KeySchema:
            - AttributeName: pr
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: !If 
          - ShouldCreateStateBackend
          - true
          - false
        SSEType: !If 
          - ShouldCreateStateBackend
          - KMS
          - !Ref AWS::NoValue
        KMSMasterKeyId: !If 
          - ShouldCreateStateBackend
          - !GetAtt KmsKey.Arn
          - !Ref AWS::NoValue

  # ============================================================================
  # GITHUB ACTIONS ACCESS
  # ============================================================================

  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: ShouldCreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateGitHubAccess
    Properties:
      RoleName: !Sub '${StackName}-${GitHubRoleName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${GitHubRepo}:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  AWSRegion:
    Description: AWS region
    Value: !Ref AWS::Region

  GitHubActionsRoleARN:
    Description: ARN of the IAM role for GitHub Actions
    Value: !If 
      - ShouldCreateGitHubAccess
      - !GetAtt GitHubActionsRole.Arn
      - ''

  PlanBucketName:
    Description: Name of the S3 bucket for plan files
    Value: !If 
      - ShouldCreatePlanFileStorage
      - !Ref PlanBucket
      - ''

  PlanDynamoDBTableName:
    Description: Name of the DynamoDB table for plan metadata
    Value: !If 
      - ShouldCreatePlanFileStorage
      - !Ref PlanDynamoDBTable
      - ''

  StackName:
    Description: Name of the stack
    Value: !Ref StackName

  StateBucketName:
    Description: Name of the S3 bucket for state storage
    Value: !If 
      - ShouldCreateStateBackend
      - !Ref StateBucket
      - ''

  StateDynamoDBTableName:
    Description: Name of the DynamoDB table for state locking
    Value: !If 
      - ShouldCreateStateBackend
      - !Ref StateDynamoDBTable
      - ''