name: Publish CloudFormation Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CLOUDFORMATION_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION}}

      - name: Upload template to S3
        run: |
          aws s3 cp templates/aws-cloudformation-terraform-backend.yaml s3://${{ vars.CLOUDFORMATION_TEMPLATE_BUCKET }}/${{ github.event.repository.name }}.yaml \
            --content-type 'application/x-yaml' \
            --cache-control 'no-cache' \
            --acl public-read \
            --sse AES256

      - name: Get template URL
        id: template-url
        run: |
          echo "url=https://${{ vars.CLOUDFORMATION_TEMPLATE_BUCKET }}.s3.amazonaws.com/${{ github.event.repository.name }}.yaml" >> $GITHUB_OUTPUT

      - name: Create CloudFormation Console URL
        id: console-url
        run: |
          TEMPLATE_URL="https://${{ vars.CLOUDFORMATION_TEMPLATE_BUCKET }}.s3.amazonaws.com/${{ github.event.repository.name }}.yaml"
          ENCODED_URL=$(echo -n "$TEMPLATE_URL" | jq -sRr @uri)
          echo "url=https://console.aws.amazon.com/cloudformation/home?region=${{ vars.AWS_REGION }}/#/stacks/create/review?templateURL=$ENCODED_URL" >> $GITHUB_OUTPUT

      - name: Report Result to GitHub Summary
        run: |
          echo "## 🚀 CloudFormation Template Published Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Template URL:** ${{ steps.template-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Launch Stack:** ${{ steps.console-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            CloudFormation template published successfully!

            ## 🚀 Deploy Complete Infrastructure
            - Template URL: ${{ steps.template-url.outputs.url }}
            - Launch Stack: ${{ steps.console-url.outputs.url }}