name: Validate CloudFormation Template

on:
  pull_request:
    paths:
      - 'templates/*.yaml'
      - '.github/workflows/validate-template.yml'

jobs:
  validate:
    name: Validate Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2

      - name: Lint CloudFormation templates
        run: |
          cfn-lint --version
          cfn-lint -t templates/*.yaml