name: Validate CloudFormation Template

on:
  pull_request:
    paths:
      - 'templates/*.yaml'
      - '.github/workflows/validate-template.yml'

jobs:
  validate:
    name: Validate Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_CLOUDFORMATION_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION}}

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://templates/aws-cloudformation-terraform-backend.yaml 