name: Validate CloudFormation Template

on:
  push:
    paths:
      - 'templates/*.yaml'
      - '.github/workflows/validate-template.yml'
  pull_request:
    paths:
      - 'templates/*.yaml'
      - '.github/workflows/validate-template.yml'

jobs:
  validate:
    name: Validate Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://templates/atmos-pro.yaml 