name: Validate CloudFormation Template

on:
  pull_request:
    paths:
      - 'templates/*.yaml'
      - '.github/workflows/validate-template.yml'

jobs:
  validate:
    name: Validate Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://templates/aws-cloudformation-terraform-backend.yaml 